// <auto-generated />
using System;
using Bridge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Bridge.Data.Migrations
{
    [DbContext(typeof(BridgeDB))]
    [Migration("20260708135728_SeedCategoriesTable")]
    partial class SeedCategoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bridge.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Bridge.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2265ea08-3732-4f73-b3b3-9945788923a7"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2886),
                            Icon = "wrench",
                            Name = "עזרה טכנית"
                        },
                        new
                        {
                            Id = new Guid("9accb771-5b17-4f3c-90a6-87f4f4ae0f64"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2925),
                            Icon = "car",
                            Name = "שינוע / קניות"
                        },
                        new
                        {
                            Id = new Guid("884a97ff-bce9-487f-8779-838c03e1fbd5"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2928),
                            Icon = "heart-pulse",
                            Name = "עזרה רפואית / ליווי"
                        },
                        new
                        {
                            Id = new Guid("84bc977f-f570-4ba8-8058-427e5f84edb0"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2931),
                            Icon = "comment-text-outline",
                            Name = "תמיכה חברתית / שיחה"
                        },
                        new
                        {
                            Id = new Guid("58fb8a21-fcf0-411e-bc32-2059bf8719c7"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2933),
                            Icon = "book-open-variant",
                            Name = "עזרה דתית / מניין"
                        },
                        new
                        {
                            Id = new Guid("f56b1564-b8d3-41fa-8227-1e4a91020dbd"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2947),
                            Icon = "home-heart",
                            Name = "אירוח / סעודות שבת"
                        },
                        new
                        {
                            Id = new Guid("25a43237-411a-4d58-9dea-b5596cf72453"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2949),
                            Icon = "food-apple",
                            Name = "אוכל כשר ומוצרים"
                        },
                        new
                        {
                            Id = new Guid("dceed682-34e8-4998-9562-63943d47f4d3"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2952),
                            Icon = "file-document-outline",
                            Name = "שפה / בירוקרטיה"
                        },
                        new
                        {
                            Id = new Guid("b23de822-12af-4164-88e9-dc4f9776a799"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2954),
                            Icon = "information-outline",
                            Name = "מידע והמלצות"
                        },
                        new
                        {
                            Id = new Guid("52eb75b6-52e1-40f7-abd6-c85f4cb2d965"),
                            CreatedAt = new DateTime(2026, 7, 8, 13, 57, 27, 72, DateTimeKind.Utc).AddTicks(2956),
                            Icon = "alert-octagon",
                            Name = "חירום / חילוץ"
                        });
                });

            modelBuilder.Entity("Bridge.Core.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Bridge.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bridge.Core.Models.Answer", b =>
                {
                    b.HasOne("Bridge.Core.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bridge.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bridge.Core.Models.Request", b =>
                {
                    b.HasOne("Bridge.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bridge.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
