// <auto-generated />
using System;
using Bridge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Bridge.Data.Migrations
{
    [DbContext(typeof(BridgeDB))]
    partial class BridgeDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bridge.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Bridge.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6cc541a-5b98-4240-9362-5a4dfd60e47d"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9256),
                            Icon = "🛠️",
                            Name = "עזרה טכנית"
                        },
                        new
                        {
                            Id = new Guid("988083e4-a6bb-460a-9b90-b0dc2a7390d4"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9327),
                            Icon = "🚗",
                            Name = "שינוע / קניות"
                        },
                        new
                        {
                            Id = new Guid("f1325d87-6c41-4b7e-b715-a3384509283d"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9330),
                            Icon = "❤️",
                            Name = "עזרה רפואית / ליווי"
                        },
                        new
                        {
                            Id = new Guid("c85f0bff-8785-436e-9124-0c4944ff829a"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9331),
                            Icon = "💬",
                            Name = "תמיכה חברתית / שיחה"
                        },
                        new
                        {
                            Id = new Guid("93b43ca5-4da2-4898-a0d2-e3b89daeeb35"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9333),
                            Icon = "📖",
                            Name = "עזרה דתית / מניין"
                        },
                        new
                        {
                            Id = new Guid("6d1f47fa-3bcd-4996-99a4-8d1a5452acdc"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9335),
                            Icon = "🏠",
                            Name = "אירוח / סעודות שבת"
                        },
                        new
                        {
                            Id = new Guid("c2e1e08d-c069-44b2-ac2c-fb5653558e26"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9336),
                            Icon = "🍎",
                            Name = "אוכל כשר ומוצרים"
                        },
                        new
                        {
                            Id = new Guid("5dacfdcf-7743-47fa-971c-e0b21c345f7d"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9347),
                            Icon = "📄",
                            Name = "שפה / בירוקרטיה"
                        },
                        new
                        {
                            Id = new Guid("3f841366-f62d-47ae-9431-e782bea00048"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9349),
                            Icon = "ℹ️",
                            Name = "מידע והמלצות"
                        },
                        new
                        {
                            Id = new Guid("e4047c16-8f18-4dd0-9578-7203a4b6a234"),
                            CreatedAt = new DateTime(2026, 7, 8, 14, 5, 14, 210, DateTimeKind.Utc).AddTicks(9350),
                            Icon = "🆘",
                            Name = "חירום / חילוץ"
                        });
                });

            modelBuilder.Entity("Bridge.Core.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Bridge.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bridge.Core.Models.Answer", b =>
                {
                    b.HasOne("Bridge.Core.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bridge.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bridge.Core.Models.Request", b =>
                {
                    b.HasOne("Bridge.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bridge.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
